# Generated by Django 5.0 on 2024-02-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Googlelogin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
