# Generated by Django 5.0 on 2024-02-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Googlelogin", "0002_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
