# Generated by Django 5.0 on 2024-02-22 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rubrop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
