# Generated by Django 5.0 on 2024-02-22 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rubrop", "0002_alter_event_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
