# Generated by Django 5.0 on 2024-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rubrop", "0003_alter_event_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
